language: java

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  - chmod +x gradlew

jobs:
  include:
    - stage: build
      script: ./gradlew build -x test
    - stage: test
      script: ./gradlew test
